version: "3.8"
services:
  linkding:
    image: sissbruecker/linkding:latest-alpine
    container_name: linkding
    restart: unless-stopped
    networks:
      - default
      - webgateway
    volumes:
      - /home/ubuntu/devbox-store/linkding:/etc/linkding/data
    labels:
      - traefik.http.routers.linkding.rule=Host(`${SUBDOMAIN}.kush.in`)
      - traefik.http.routers.linkding.tls=true
      - traefik.http.routers.linkding.tls.certResolver=letsencrypt
      - traefik.http.services.linkding.loadbalancer.server.port=9090
networks:
  webgateway:
    external: true
